# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# # docker-compose up -d

services:

  arango-vector-db:
    image: arangodb/arangodb:3.12.4
    container_name: arango-vector-db
    ports:
      - "8529:8529"
    volumes:
      - /root/arango_data:/var/lib/arangodb3
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD}
    # https://docs.arangodb.com/3.12/components/arangodb-server/options/
    command: ["--experimental-vector-index=true"]
    restart: unless-stopped
    networks:
      - chatqna_default

networks:
  chatqna_default:
    driver: bridge
    name: chatqna_default
    external: true

volumes:
  arango_data: